### PR TITLE
Add support for FFmpeg 7.0

### PR DESCRIPTION
**Pull request by AdrianEddy**
This PR adds support for FFmpeg 7.0 and updates dependencies

### CODE REVIEW

**Comment by Polochon-street** [comment]
Hi,

Thanks a lot for taking care of that :) I updated the CI to the "official" ubuntu with ffmpeg 6.1, but I don't think even unofficial builds for 7 are out yet?

I was thinking to wait til the builds are out, and then resurrect https://github.com/zmwangx/rust-ffmpeg-sys/pull/74/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L42-L77, replacing 6 by 7. What do you think?

**Comment by AdrianEddy** [comment]
> I was thinking to wait til the builds are out, and then resurrect https://github.com/zmwangx/rust-ffmpeg-sys/pull/74/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L42-L77, replacing 6 by 7. What do you think?

Yes, that's a good way, but even that ppa doesn't have ffmpeg 7.0 yet. I guess I'm ahead of everyone else :)
I personally use builds from [avbuild](https://sourceforge.net/projects/avbuild/files/)

**Comment by Polochon-street** [comment]
ah, nice! Do you think you could make it work with ffmpeg 7.0? Or we could also wait until that PPA has ffmpeg 7.0 :)

**Comment by AdrianEddy** [comment]
Ok looks like it now works in the CI with a build from avbuild. Please squash when merging

**Comment by Polochon-street** [comment]
thanks for working on that! Let's try it.

**Pull request merged**
